### ISSUE TITLE
Twitter feed is connected to Cleonix. Should be connected to the MACUCC page

### ISSUE THREAD

**Issue by camerontrimble** [camerontrimble/Dashboard-Project#19]
![screenshot 2016-05-28 14 31 27](https://cloud.githubusercontent.com/assets/15096099/15629208/ee69399a-24e0-11e6-8f44-4dc50946e882.png)

**Comment by debdiproy** [comment]
For this I need access to their twitter account so basically I need their Twitter username and password.
