### ISSUE TITLE
Send test email

### ISSUE THREAD

**Issue by camerontrimble** [camerontrimble/Dashboard-Project#38]
Dawn will need a way to send a test email to herself to make sure that it looks the way she wants. I don't see a way to do that right now. 

And when I click on any links in the email, it makes me log in again.

**Comment by debdiproy** [comment]
Completed

**Comment by debdiproy** [comment]
![macucc surveysettings - faith trends 2016-07-26 22-57-33](https://cloud.githubusercontent.com/assets/15095068/17148328/5f9197c6-5384-11e6-9f92-64cba1c655d5.png)
