### ISSUE TITLE
If I want to send a survey out to a group once, I don't see a way to do that. 

### ISSUE THREAD

**Issue by camerontrimble** [camerontrimble/Dashboard-Project#44]
I think we need to design a new section that says "Get Results."

On that page we have something that looks like this:
![screen shot 2016-07-08 at 2 30 53 pm](https://cloud.githubusercontent.com/assets/15096099/16697646/a949082e-4518-11e6-8e2d-e82e6c825c86.png)

Ours needs to be:

Track Trends - Use FaithTrends to send emails according to your custom frequencies to users associated with this survey.

Send by Weblink - Get a custom weblink to this survey that you can send out on your own.

Embed on my Website - Get the embed code that allows people to complete this survey on your website.

Share on Social Media - Share this survey through your social media accounts (Facebook, Twitter, etc.) to collect responses. 

Add Data Manually - Best option for in-house admin to add data to survey.

**Comment by debdiproy** [comment]
This section will complete by tomorrow
