### ISSUE TITLE
Create payment system for new accounts

### ISSUE THREAD

**Issue by camerontrimble** [camerontrimble/Dashboard-Project#50]

**Comment by debdiproy** [comment]
We have setup a basic Paypal system from the user profile billing tab:

![pay with a credit or debit card - paypal 2016-07-26 22-59-59](https://cloud.githubusercontent.com/assets/15095068/17148431/ca7f6ec8-5384-11e6-8979-775002d5b917.png)
![profile - faith trends 2016-07-26 22-59-38](https://cloud.githubusercontent.com/assets/15095068/17148430/ca7bd93e-5384-11e6-898a-02c22b55f0a4.png)
